name: common

services:
  image: redis:latest
  container_name: redis
  restart: always
  ports:
    - 6379:6379
  volumes:
    - redis_data:/data
  networks:
    - common

  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sketch_app
      - POSTGRES_PASSWORD=password@123
    ports:
      - '5432:5432'
    healthcheck:
      test: [ 'CMD', 'pg_isready' ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - common
      
  postgres-slave:
    image: postgres:latest
    container_name: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sketch_app
      - POSTGRES_PASSWORD=password@123
    ports:
      - '5434:5432'
    healthcheck:
      test: [ 'CMD', 'pg_isready' ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - common

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - '8888:80'
    restart: unless-stopped
    networks:
      - common

volumes:
  postgres:
  pgadmin:
  redis_data:


networks:
  common:
    driver: bridge
    external: true
